### ISSUE TITLE
シミュレータ上のラズパイマウスを動かす方法 Part5が実行できない。

### ISSUE THREAD

**Issue by ba2vwbus13** [yukixx6/raspimouse_sim_tutorial#14]
シミュレータ上のラズパイマウスを動かす方法 Part5
rosservice call /motor_on を行うと、
ERROR: Service [/motor_on] is not available.となります
rosservice listは次となり、/motor_onが入ってません。
ーーー
/gazebo/apply_body_wrench
/gazebo/apply_joint_effort
。。。
ーーー
また、rosrun raspimouse_sim_tutorial_program left_hand.pyを実行してもマウスは動きません。

修正方法がありましたら、教えていただけますでしょうか。

**Comment by ba2vwbus13** [comment]
roslaunch raspimouse_ros_2 raspimouse.launch
を実行したら動きました。

**Comment by yukixx6** [comment]
報告ありがとうございます。
修正します。
